name: intern_progress_analyzer
description: A Flutter app for analyzing and tracking intern progress using AI.
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP requests to connect with Flask backend
  http: ^1.2.2

  # State management
  provider: ^6.1.2

  # Local data storage (for login/session)
  shared_preferences: ^2.3.2

  # Beautiful charts for dashboards
  fl_chart: ^0.69.0

  # JSON handling (backend data parsing)
  json_annotation: ^4.9.0

  # UI and animations
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  animations: ^2.0.11

  # For navigation and routes
  go_router: ^14.2.0

  # For app icons and UI widgets
  iconsax: ^0.0.8
  flutter_svg: ^2.0.10

  # Responsive design
  responsive_framework: ^1.2.0

  # Optional – For connectivity checking (useful when backend is offline)
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
