INSERT INTO logbook_entries (intern_id, date, status, task_stack, todays_work, challenges, tomorrow_plan)
VALUES
(8, '2025-09-12', 'Working', 'DevOps', 'Resolved login deployment issues', 'Debugging API calls problem', 'Plan to testing'),
(6, '2025-09-04', 'Working', 'UIUX', 'Updated UI mockups', 'Debugging state management problem', 'Focus on review tomorrow'),
(3, '2025-10-20', 'Working', 'UIUX', 'Tested service prototype usability', 'Facing difficulty in deployment', 'Next, will work on coding'),
(10, '2025-09-08', 'WFH', 'Backend', 'Integrated API module with authentication', 'Encountered issues with deployment', 'Continue integration tasks'),
(9, '2025-08-31', 'Leave', 'Backend', 'Implemented UI service logic', 'Pending API calls integration', 'Plan to review'),
(1, '2025-09-09', 'Working', 'DevOps', 'Set up monitoring for service service', 'Encountered issues with state management', 'Focus on documentation tomorrow'),
(1, '2025-10-18', 'WFH', 'DevOps', 'Resolved component deployment issues', 'Encountered issues with deployment', 'Continue design tasks'),
(8, '2025-09-09', 'Working', 'DevOps', 'Configured feature CI/CD pipeline', 'Facing difficulty in integration', 'Plan to design'),
(6, '2025-10-21', 'Working', 'Other', 'Documented dashboard process', 'Pending integration integration', 'Plan to review'),
(5, '2025-09-22', 'Working', 'Frontend', 'Refactored dashboard layout for responsiveness', 'Encountered issues with API calls', 'Plan to testing'),
(6, '2025-08-26', 'Working', 'UIUX', 'Tested component prototype usability', 'Debugging deployment problem', 'Focus on review tomorrow'),
(8, '2025-09-08', 'Working', 'Backend', 'Created login API endpoint', 'Facing difficulty in data processing', 'Plan to coding'),
(4, '2025-09-07', 'Working', 'DataScience', 'Trained component model', 'Debugging UI layout problem', 'Continue integration tasks'),
(5, '2025-09-27', 'Working', 'Frontend', 'Refactored dashboard layout for responsiveness', 'Facing difficulty in API calls', 'Focus on integration tomorrow'),
(8, '2025-09-23', 'Working', 'DevOps', 'Resolved feature deployment issues', 'Debugging API calls problem', 'Plan to coding'),
(9, '2025-08-23', 'Working', 'Other', 'Reviewed UI pull requests', 'Encountered issues with state management', 'Focus on coding tomorrow'),
(5, '2025-09-10', 'Leave', 'Other', 'Reviewed component pull requests', 'Pending integration integration', 'Continue integration tasks'),
(10, '2025-09-03', 'Working', 'DataScience', 'Performed UI data cleaning', 'Encountered issues with integration', 'Next, will work on documentation'),
(6, '2025-08-25', 'WFH', 'DataScience', 'Conducted feature engineering on component dataset', 'Encountered issues with deployment', 'Plan to testing'),
(3, '2025-09-28', 'WFH', 'Frontend', 'Implemented UI page UI', 'Facing difficulty in deployment', 'Plan to testing'),
(9, '2025-09-12', 'WFH', 'Backend', 'Created UI API endpoint', 'Pending integration integration', 'Focus on coding tomorrow'),
(4, '2025-09-25', 'WFH', 'DataScience', 'Trained model model', 'Debugging data processing problem', 'Plan to testing'),
(5, '2025-09-26', 'WFH', 'DataScience', 'Performed service data cleaning', 'Pending UI layout integration', 'Plan to documentation'),
(4, '2025-08-28', 'Working', 'Backend', 'Optimized component database queries', 'Pending data processing integration', 'Continue coding tasks'),
(5, '2025-08-22', 'Working', 'DevOps', 'Deployed login service to staging', 'Facing difficulty in integration', 'Continue testing tasks'),
(8, '2025-08-24', 'Working', 'UIUX', 'Designed model wireframes', 'Encountered issues with deployment', 'Continue testing tasks'),
(2, '2025-10-21', 'Working', 'Frontend', 'Implemented model page UI', 'Debugging state management problem', 'Plan to documentation'),
(6, '2025-10-10', 'Working', 'UIUX', 'Improved model user interaction flows', 'Debugging API calls problem', 'Next, will work on documentation'),
(7, '2025-10-02', 'Working', 'DevOps', 'Resolved service deployment issues', 'Debugging integration problem', 'Next, will work on testing'),
(6, '2025-10-19', 'Working', 'DevOps', 'Set up monitoring for API service', 'Pending API calls integration', 'Next, will work on coding'),
(5, '2025-08-24', 'Working', 'Backend', 'Created login API endpoint', 'Debugging integration problem', 'Next, will work on documentation'),
(6, '2025-10-03', 'Working', 'Other', 'Worked on login task', 'Encountered issues with deployment', 'Focus on design tomorrow'),
(5, '2025-09-10', 'WFH', 'DataScience', 'Trained feature model', 'Pending data processing integration', 'Focus on testing tomorrow'),
(10, '2025-09-12', 'WFH', 'Other', 'Documented API process', 'Pending data processing integration', 'Focus on coding tomorrow'),
(5, '2025-10-10', 'WFH', 'Backend', 'Optimized feature database queries', 'Encountered issues with state management', 'Plan to review'),
(4, '2025-08-21', 'Working', 'UIUX', 'Tested model prototype usability', 'Encountered issues with API calls', 'Focus on testing tomorrow'),
(6, '2025-08-26', 'Leave', 'Backend', 'Created login API endpoint', 'Facing difficulty in API calls', 'Focus on testing tomorrow'),
(8, '2025-10-13', 'WFH', 'Other', 'Worked on model task', 'Facing difficulty in UI layout', 'Continue review tasks'),
(10, '2025-10-19', 'Leave', 'Other', 'Attended service meeting', 'Pending integration integration', 'Focus on review tomorrow'),
(8, '2025-10-09', 'WFH', 'Other', 'Documented login process', 'Pending API calls integration', 'Continue testing tasks'),
(9, '2025-09-26', 'Working', 'UIUX', 'Updated login mockups', 'Encountered issues with integration', 'Continue integration tasks'),
(1, '2025-09-11', 'Working', 'Other', 'Worked on login task', 'Encountered issues with deployment', 'Next, will work on testing'),
(4, '2025-08-25', 'Working', 'Backend', 'Implemented feature service logic', 'Encountered issues with UI layout', 'Focus on testing tomorrow'),
(5, '2025-10-12', 'Working', 'UIUX', 'Updated component mockups', 'Debugging deployment problem', 'Plan to testing'),
(8, '2025-09-13', 'WFH', 'UIUX', 'Designed UI wireframes', 'Facing difficulty in integration', 'Focus on integration tomorrow'),
(1, '2025-09-10', 'Working', 'DataScience', 'Trained API model', 'Encountered issues with state management', 'Continue integration tasks'),
(7, '2025-09-13', 'Working', 'Frontend', 'Refactored component layout for responsiveness', 'Debugging deployment problem', 'Next, will work on testing'),
(10, '2025-10-16', 'Working', 'DevOps', 'Resolved login deployment issues', 'Encountered issues with state management', 'Continue integration tasks'),
(9, '2025-08-21', 'Working', 'Backend', 'Implemented feature service logic', 'Encountered issues with UI layout', 'Focus on testing tomorrow'),
(7, '2025-10-08', 'Working', 'Backend', 'Optimized login database queries', 'Encountered issues with API calls', 'Focus on design tomorrow'),
(6, '2025-08-26', 'WFH', 'UIUX', 'Tested component prototype usability', 'Pending API calls integration', 'Focus on review tomorrow'),
(4, '2025-10-03', 'WFH', 'DataScience', 'Performed login data cleaning', 'Pending UI layout integration', 'Next, will work on review'),
(3, '2025-09-26', 'Working', 'UIUX', 'Updated dashboard mockups', 'Facing difficulty in state management', 'Plan to review'),
(7, '2025-09-19', 'Working', 'DataScience', 'Evaluated model algorithm accuracy', 'Encountered issues with API calls', 'Next, will work on integration'),
(10, '2025-09-21', 'Working', 'Frontend', 'Added feature button functionality', 'Facing difficulty in integration', 'Continue documentation tasks'),
(6, '2025-10-18', 'Working', 'UIUX', 'Updated feature mockups', 'Pending UI layout integration', 'Next, will work on testing'),
(7, '2025-09-06', 'Working', 'DevOps', 'Deployed UI service to staging', 'Pending deployment integration', 'Next, will work on coding'),
(2, '2025-09-20', 'Working', 'Other', 'Reviewed API pull requests', 'Encountered issues with state management', 'Continue design tasks'),
(4, '2025-08-31', 'WFH', 'DevOps', 'Configured API CI/CD pipeline', 'Facing difficulty in data processing', 'Continue documentation tasks'),
(4, '2025-10-14', 'Working', 'Other', 'Worked on dashboard task', 'Facing difficulty in state management', 'Next, will work on integration'),
(8, '2025-08-26', 'Working', 'Frontend', 'Refactored API layout for responsiveness', 'Debugging deployment problem', 'Plan to documentation'),
(1, '2025-09-05', 'Working', 'Backend', 'Created UI API endpoint', 'Pending UI layout integration', 'Plan to design'),
(7, '2025-09-02', 'Working', 'Backend', 'Integrated API module with authentication', 'Pending API calls integration', 'Next, will work on review'),
(2, '2025-09-30', 'Leave', 'DataScience', 'Evaluated component algorithm accuracy', 'Pending deployment integration', 'Next, will work on review'),
(9, '2025-09-09', 'WFH', 'DataScience', 'Performed model data cleaning', 'Debugging data processing problem', 'Focus on coding tomorrow'),
(6, '2025-09-24', 'Leave', 'Frontend', 'Implemented model page UI', 'Encountered issues with data processing', 'Focus on coding tomorrow'),
(2, '2025-09-05', 'Working', 'DevOps', 'Resolved component deployment issues', 'Pending UI layout integration', 'Focus on coding tomorrow'),
(3, '2025-09-25', 'WFH', 'DataScience', 'Trained API model', 'Debugging UI layout problem', 'Focus on coding tomorrow'),
(10, '2025-09-06', 'Working', 'DataScience', 'Conducted feature engineering on service dataset', 'Facing difficulty in UI layout', 'Plan to coding'),
(3, '2025-09-29', 'Working', 'DataScience', 'Performed dashboard data cleaning', 'Facing difficulty in integration', 'Focus on testing tomorrow'),
(10, '2025-10-12', 'Working', 'UIUX', 'Tested feature prototype usability', 'Pending data processing integration', 'Plan to review'),
(7, '2025-10-12', 'Working', 'Backend', 'Optimized login database queries', 'Debugging deployment problem', 'Plan to design'),
(10, '2025-09-05', 'Working', 'Frontend', 'Added UI button functionality', 'Debugging data processing problem', 'Next, will work on documentation'),
(9, '2025-10-20', 'Working', 'DataScience', 'Evaluated login algorithm accuracy', 'Encountered issues with deployment', 'Plan to review'),
(7, '2025-09-23', 'Working', 'DevOps', 'Resolved service deployment issues', 'Pending data processing integration', 'Focus on review tomorrow'),
(5, '2025-09-29', 'WFH', 'Backend', 'Integrated dashboard module with authentication', 'Encountered issues with integration', 'Focus on documentation tomorrow'),
(5, '2025-08-31', 'Working', 'Backend', 'Optimized API database queries', 'Debugging state management problem', 'Plan to review'),
(10, '2025-09-14', 'Leave', 'Backend', 'Integrated login module with authentication', 'Pending integration integration', 'Focus on testing tomorrow'),
(5, '2025-10-21', 'Working', 'UIUX', 'Tested feature prototype usability', 'Facing difficulty in deployment', 'Next, will work on design'),
(8, '2025-10-13', 'Working', 'UIUX', 'Improved model user interaction flows', 'Encountered issues with integration', 'Next, will work on design'),
(6, '2025-08-31', 'WFH', 'DevOps', 'Resolved service deployment issues', 'Facing difficulty in deployment', 'Next, will work on integration'),
(9, '2025-08-31', 'Working', 'DevOps', 'Set up monitoring for component service', 'Pending UI layout integration', 'Next, will work on review'),
(2, '2025-09-29', 'Leave', 'DevOps', 'Set up monitoring for login service', 'Pending UI layout integration', 'Plan to documentation'),
(10, '2025-08-27', 'Working', 'Frontend', 'Fixed component component styling', 'Pending integration integration', 'Plan to documentation'),
(6, '2025-10-19', 'Working', 'DataScience', 'Performed login data cleaning', 'Debugging integration problem', 'Next, will work on review'),
(5, '2025-10-13', 'Working', 'UIUX', 'Designed UI wireframes', 'Debugging state management problem', 'Plan to design'),
(9, '2025-08-24', 'Working', 'Other', 'Documented model process', 'Pending UI layout integration', 'Continue coding tasks'),
(9, '2025-09-07', 'Working', 'UIUX', 'Designed model wireframes', 'Encountered issues with UI layout', 'Continue design tasks'),
(2, '2025-10-13', 'Working', 'Backend', 'Created dashboard API endpoint', 'Encountered issues with data processing', 'Next, will work on testing'),
(9, '2025-08-23', 'Working', 'Other', 'Worked on API task', 'Encountered issues with state management', 'Continue integration tasks'),
(4, '2025-09-06', 'Working', 'DevOps', 'Configured login CI/CD pipeline', 'Debugging UI layout problem', 'Continue integration tasks'),
(2, '2025-09-18', 'Working', 'DataScience', 'Trained API model', 'Pending state management integration', 'Continue design tasks'),
(4, '2025-09-23', 'Working', 'DataScience', 'Performed login data cleaning', 'Pending state management integration', 'Continue design tasks'),
(2, '2025-08-26', 'WFH', 'UIUX', 'Improved UI user interaction flows', 'Facing difficulty in deployment', 'Plan to design'),
(9, '2025-10-17', 'Working', 'Other', 'Reviewed model pull requests', 'Encountered issues with state management', 'Next, will work on integration'),
(7, '2025-08-29', 'Working', 'DataScience', 'Conducted feature engineering on login dataset', 'Encountered issues with UI layout', 'Focus on integration tomorrow'),
(5, '2025-09-03', 'WFH', 'Backend', 'Created feature API endpoint', 'Pending state management integration', 'Focus on review tomorrow'),
(6, '2025-09-03', 'Working', 'DataScience', 'Evaluated API algorithm accuracy', 'Pending data processing integration', 'Focus on testing tomorrow'),
(8, '2025-10-03', 'Working', 'UIUX', 'Updated API mockups', 'Debugging UI layout problem', 'Next, will work on design'),
(4, '2025-09-21', 'WFH', 'Other', 'Attended component meeting', 'Debugging deployment problem', 'Next, will work on integration'),
(7, '2025-09-03', 'Working', 'UIUX', 'Designed API wireframes', 'Encountered issues with deployment', 'Continue documentation tasks'),
(10, '2025-09-24', 'Working', 'DataScience', 'Conducted feature engineering on login dataset', 'Encountered issues with data processing', 'Continue documentation tasks'),
(3, '2025-10-01', 'Working', 'Backend', 'Implemented model service logic', 'Encountered issues with state management', 'Focus on testing tomorrow'),
(4, '2025-09-15', 'Working', 'UIUX', 'Updated feature mockups', 'Debugging state management problem', 'Next, will work on integration'),
(5, '2025-09-25', 'Working', 'UIUX', 'Improved feature user interaction flows', 'Encountered issues with API calls', 'Continue documentation tasks'),
(1, '2025-09-09', 'Working', 'Frontend', 'Implemented API page UI', 'Facing difficulty in deployment', 'Plan to review'),
(9, '2025-09-05', 'Leave', 'Backend', 'Implemented API service logic', 'Pending state management integration', 'Continue integration tasks'),
(3, '2025-10-06', 'Working', 'Other', 'Reviewed feature pull requests', 'Pending deployment integration', 'Continue documentation tasks'),
(1, '2025-09-26', 'Working', 'Other', 'Reviewed API pull requests', 'Debugging API calls problem', 'Next, will work on testing'),
(2, '2025-09-18', 'WFH', 'DevOps', 'Deployed login service to staging', 'Debugging state management problem', 'Focus on review tomorrow'),
(7, '2025-08-20', 'Working', 'Frontend', 'Fixed login component styling', 'Encountered issues with data processing', 'Focus on design tomorrow'),
(10, '2025-08-26', 'Working', 'Backend', 'Created API API endpoint', 'Pending API calls integration', 'Plan to testing'),
(3, '2025-08-30', 'Working', 'Other', 'Reviewed model pull requests', 'Pending deployment integration', 'Plan to integration'),
(6, '2025-09-18', 'Working', 'UIUX', 'Updated feature mockups', 'Facing difficulty in API calls', 'Next, will work on design'),
(7, '2025-08-27', 'Working', 'DataScience', 'Performed model data cleaning', 'Facing difficulty in API calls', 'Focus on integration tomorrow'),
(6, '2025-10-19', 'Leave', 'DevOps', 'Deployed login service to staging', 'Facing difficulty in deployment', 'Focus on testing tomorrow'),
(6, '2025-09-15', 'Working', 'Frontend', 'Added feature button functionality', 'Pending state management integration', 'Next, will work on testing'),
(2, '2025-10-17', 'Working', 'DataScience', 'Performed feature data cleaning', 'Debugging integration problem', 'Focus on review tomorrow'),
(10, '2025-08-20', 'WFH', 'Frontend', 'Added component button functionality', 'Facing difficulty in deployment', 'Continue integration tasks'),
(5, '2025-10-17', 'WFH', 'Frontend', 'Implemented service page UI', 'Debugging deployment problem', 'Next, will work on testing'),
(2, '2025-10-15', 'Working', 'DataScience', 'Conducted feature engineering on API dataset', 'Debugging data processing problem', 'Continue documentation tasks'),
(6, '2025-10-14', 'Working', 'Frontend', 'Implemented UI page UI', 'Encountered issues with API calls', 'Plan to testing'),
(3, '2025-10-20', 'Working', 'UIUX', 'Designed API wireframes', 'Encountered issues with data processing', 'Continue design tasks'),
(9, '2025-10-08', 'Working', 'DataScience', 'Performed UI data cleaning', 'Encountered issues with deployment', 'Next, will work on design'),
(6, '2025-10-19', 'Working', 'DevOps', 'Deployed model service to staging', 'Pending UI layout integration', 'Focus on documentation tomorrow'),
(1, '2025-09-03', 'Working', 'Frontend', 'Implemented feature page UI', 'Debugging deployment problem', 'Focus on coding tomorrow'),
(8, '2025-10-11', 'Working', 'Other', 'Reviewed model pull requests', 'Encountered issues with state management', 'Plan to integration'),
(5, '2025-08-19', 'Working', 'Backend', 'Created login API endpoint', 'Facing difficulty in data processing', 'Continue documentation tasks'),
(6, '2025-09-21', 'Working', 'UIUX', 'Improved model user interaction flows', 'Encountered issues with deployment', 'Next, will work on design'),
(1, '2025-09-29', 'Working', 'Other', 'Attended API meeting', 'Encountered issues with integration', 'Next, will work on review'),
(7, '2025-10-04', 'Working', 'Backend', 'Integrated dashboard module with authentication', 'Facing difficulty in integration', 'Plan to coding'),
(4, '2025-10-03', 'Working', 'Other', 'Attended service meeting', 'Pending UI layout integration', 'Next, will work on testing'),
(1, '2025-09-01', 'Working', 'DataScience', 'Trained model model', 'Encountered issues with integration', 'Plan to testing'),
(7, '2025-10-13', 'Working', 'Other', 'Documented login process', 'Facing difficulty in API calls', 'Next, will work on documentation'),
(3, '2025-10-16', 'Working', 'Backend', 'Optimized service database queries', 'Pending API calls integration', 'Continue review tasks'),
(4, '2025-10-21', 'Leave', 'Other', 'Attended API meeting', 'Facing difficulty in UI layout', 'Focus on review tomorrow'),
(3, '2025-09-17', 'Working', 'Backend', 'Implemented model service logic', 'Debugging API calls problem', 'Next, will work on integration'),
(8, '2025-09-16', 'Working', 'Other', 'Worked on component task', 'Encountered issues with state management', 'Plan to design'),
(6, '2025-10-04', 'Working', 'DataScience', 'Evaluated model algorithm accuracy', 'Encountered issues with integration', 'Plan to review'),
(9, '2025-08-26', 'Working', 'DevOps', 'Set up monitoring for component service', 'Encountered issues with API calls', 'Plan to coding'),
(7, '2025-09-01', 'WFH', 'DevOps', 'Resolved UI deployment issues', 'Encountered issues with state management', 'Plan to review'),
(8, '2025-09-30', 'Working', 'Backend', 'Created login API endpoint', 'Pending API calls integration', 'Plan to review'),
(10, '2025-10-08', 'Working', 'DataScience', 'Evaluated login algorithm accuracy', 'Pending deployment integration', 'Plan to integration'),
(5, '2025-08-20', 'Working', 'DataScience', 'Trained UI model', 'Debugging data processing problem', 'Next, will work on design'),
(3, '2025-08-27', 'Working', 'Backend', 'Optimized feature database queries', 'Encountered issues with data processing', 'Focus on review tomorrow'),
(5, '2025-08-26', 'Working', 'DevOps', 'Configured login CI/CD pipeline', 'Debugging state management problem', 'Continue integration tasks'),
(6, '2025-10-09', 'Working', 'DevOps', 'Deployed API service to staging', 'Facing difficulty in deployment', 'Plan to review'),
(2, '2025-09-08', 'Working', 'Other', 'Reviewed login pull requests', 'Facing difficulty in deployment', 'Plan to design'),
(8, '2025-09-04', 'Working', 'Frontend', 'Refactored dashboard layout for responsiveness', 'Encountered issues with deployment', 'Focus on coding tomorrow'),
(10, '2025-09-24', 'Working', 'Backend', 'Created dashboard API endpoint', 'Facing difficulty in deployment', 'Focus on review tomorrow'),
(8, '2025-10-09', 'Working', 'Backend', 'Implemented service service logic', 'Pending UI layout integration', 'Plan to coding'),
(10, '2025-09-23', 'Working', 'Frontend', 'Added login button functionality', 'Pending UI layout integration', 'Next, will work on integration'),
(7, '2025-09-16', 'Leave', 'Backend', 'Implemented feature service logic', 'Pending API calls integration', 'Next, will work on review'),
(1, '2025-08-23', 'Working', 'UIUX', 'Designed feature wireframes', 'Encountered issues with integration', 'Plan to documentation'),
(4, '2025-10-11', 'Working', 'Other', 'Documented dashboard process', 'Facing difficulty in state management', 'Plan to testing'),
(7, '2025-08-24', 'Working', 'DataScience', 'Performed UI data cleaning', 'Encountered issues with UI layout', 'Continue coding tasks'),
(8, '2025-08-24', 'Working', 'DevOps', 'Resolved UI deployment issues', 'Pending deployment integration', 'Focus on documentation tomorrow'),
(5, '2025-10-16', 'Working', 'Backend', 'Created login API endpoint', 'Facing difficulty in API calls', 'Focus on integration tomorrow'),
(7, '2025-09-26', 'Working', 'DataScience', 'Performed API data cleaning', 'Pending API calls integration', 'Plan to documentation'),
(2, '2025-10-07', 'Leave', 'DataScience', 'Trained model model', 'Encountered issues with state management', 'Focus on design tomorrow'),
(4, '2025-09-08', 'Working', 'Frontend', 'Added UI button functionality', 'Encountered issues with UI layout', 'Continue testing tasks'),
(10, '2025-10-08', 'WFH', 'UIUX', 'Tested service prototype usability', 'Facing difficulty in state management', 'Focus on design tomorrow'),
(6, '2025-08-27', 'WFH', 'DataScience', 'Conducted feature engineering on feature dataset', 'Pending state management integration', 'Next, will work on coding'),
(2, '2025-09-16', 'Working', 'Frontend', 'Added login button functionality', 'Encountered issues with UI layout', 'Next, will work on testing'),
(5, '2025-09-20', 'Working', 'Backend', 'Implemented model service logic', 'Debugging data processing problem', 'Continue documentation tasks'),
(3, '2025-08-30', 'WFH', 'Frontend', 'Added feature button functionality', 'Facing difficulty in state management', 'Next, will work on testing'),
(7, '2025-09-17', 'Working', 'DevOps', 'Deployed UI service to staging', 'Facing difficulty in state management', 'Next, will work on documentation'),
(7, '2025-08-21', 'Leave', 'UIUX', 'Designed service wireframes', 'Encountered issues with state management', 'Continue integration tasks'),
(7, '2025-10-21', 'Working', 'Other', 'Worked on API task', 'Encountered issues with deployment', 'Plan to testing'),
(1, '2025-09-13', 'Working', 'Backend', 'Created UI API endpoint', 'Facing difficulty in deployment', 'Focus on review tomorrow'),
(3, '2025-09-06', 'Working', 'DevOps', 'Set up monitoring for component service', 'Facing difficulty in state management', 'Next, will work on coding'),
(8, '2025-09-21', 'Working', 'Backend', 'Optimized service database queries', 'Encountered issues with UI layout', 'Plan to design'),
(6, '2025-08-22', 'Working', 'DataScience', 'Conducted feature engineering on model dataset', 'Pending API calls integration', 'Next, will work on design'),
(3, '2025-09-06', 'Working', 'Other', 'Worked on UI task', 'Debugging data processing problem', 'Plan to integration'),
(5, '2025-09-28', 'Working', 'Other', 'Documented model process', 'Pending UI layout integration', 'Focus on documentation tomorrow'),
(10, '2025-09-14', 'Working', 'Other', 'Attended UI meeting', 'Pending UI layout integration', 'Focus on design tomorrow'),
(7, '2025-10-20', 'WFH', 'DevOps', 'Set up monitoring for API service', 'Encountered issues with deployment', 'Focus on integration tomorrow'),
(2, '2025-09-24', 'Leave', 'UIUX', 'Improved feature user interaction flows', 'Debugging state management problem', 'Next, will work on design'),
(4, '2025-09-11', 'Working', 'Other', 'Worked on service task', 'Debugging API calls problem', 'Plan to design'),
(5, '2025-09-15', 'Working', 'DevOps', 'Deployed model service to staging', 'Facing difficulty in integration', 'Next, will work on testing'),
(2, '2025-08-25', 'Working', 'Frontend', 'Refactored login layout for responsiveness', 'Debugging state management problem', 'Next, will work on review'),
(1, '2025-09-15', 'Leave', 'Other', 'Documented API process', 'Pending API calls integration', 'Next, will work on review'),
(2, '2025-08-26', 'Working', 'Frontend', 'Added UI button functionality', 'Pending deployment integration', 'Continue coding tasks'),
(8, '2025-09-17', 'Working', 'DataScience', 'Conducted feature engineering on model dataset', 'Pending UI layout integration', 'Next, will work on review'),
(1, '2025-10-16', 'WFH', 'Backend', 'Integrated feature module with authentication', 'Facing difficulty in state management', 'Plan to testing'),
(10, '2025-08-29', 'Working', 'Other', 'Attended feature meeting', 'Facing difficulty in integration', 'Focus on design tomorrow'),
(1, '2025-09-23', 'Working', 'Backend', 'Integrated login module with authentication', 'Encountered issues with integration', 'Plan to integration'),
(6, '2025-08-30', 'WFH', 'Other', 'Attended feature meeting', 'Debugging data processing problem', 'Focus on design tomorrow'),
(8, '2025-08-26', 'Working', 'Frontend', 'Implemented component page UI', 'Encountered issues with UI layout', 'Next, will work on integration'),
(4, '2025-09-20', 'Working', 'UIUX', 'Designed component wireframes', 'Pending UI layout integration', 'Continue integration tasks'),
(9, '2025-10-21', 'Working', 'Backend', 'Integrated service module with authentication', 'Encountered issues with API calls', 'Continue integration tasks'),
(3, '2025-10-20', 'Working', 'Backend', 'Implemented service service logic', 'Encountered issues with state management', 'Focus on coding tomorrow'),
(4, '2025-08-29', 'Working', 'Backend', 'Optimized model database queries', 'Debugging state management problem', 'Plan to integration'),
(1, '2025-10-09', 'WFH', 'Other', 'Documented component process', 'Encountered issues with API calls', 'Next, will work on coding'),
(8, '2025-09-12', 'Working', 'UIUX', 'Tested component prototype usability', 'Debugging integration problem', 'Focus on integration tomorrow'),
(2, '2025-10-02', 'Leave', 'DevOps', 'Configured login CI/CD pipeline', 'Pending UI layout integration', 'Continue testing tasks'),
(3, '2025-09-19', 'Working', 'DataScience', 'Performed API data cleaning', 'Debugging integration problem', 'Focus on testing tomorrow'),
(9, '2025-09-07', 'Working', 'DataScience', 'Trained login model', 'Pending UI layout integration', 'Continue coding tasks'),
(3, '2025-10-09', 'Working', 'DataScience', 'Conducted feature engineering on API dataset', 'Debugging API calls problem', 'Continue integration tasks'),
(7, '2025-09-14', 'Working', 'Backend', 'Created API API endpoint', 'Encountered issues with integration', 'Plan to design'),
(8, '2025-09-19', 'Working', 'Other', 'Documented feature process', 'Pending deployment integration', 'Next, will work on documentation'),
(5, '2025-09-12', 'WFH', 'Backend', 'Implemented feature service logic', 'Facing difficulty in integration', 'Focus on design tomorrow'),
(4, '2025-09-24', 'Working', 'Other', 'Reviewed model pull requests', 'Pending deployment integration', 'Focus on integration tomorrow'),
(6, '2025-09-29', 'Working', 'Other', 'Attended API meeting', 'Debugging integration problem', 'Next, will work on testing'),
(1, '2025-09-17', 'WFH', 'Backend', 'Integrated service module with authentication', 'Pending integration integration', 'Focus on testing tomorrow'),
(2, '2025-09-13', 'Working', 'Backend', 'Implemented login service logic', 'Encountered issues with state management', 'Continue design tasks'),
(7, '2025-09-03', 'WFH', 'DataScience', 'Trained component model', 'Facing difficulty in API calls', 'Continue integration tasks'),
(3, '2025-10-01', 'Working', 'UIUX', 'Updated API mockups', 'Encountered issues with API calls', 'Next, will work on review'),
(6, '2025-09-13', 'Working', 'Other', 'Documented login process', 'Facing difficulty in state management', 'Next, will work on integration'),
(2, '2025-09-16', 'WFH', 'Other', 'Documented UI process', 'Debugging API calls problem', 'Plan to coding'),
(7, '2025-10-14', 'Leave', 'DevOps', 'Set up monitoring for component service', 'Pending deployment integration', 'Focus on design tomorrow'),
(6, '2025-08-23', 'Working', 'DevOps', 'Configured UI CI/CD pipeline', 'Facing difficulty in state management', 'Next, will work on testing'),
(4, '2025-10-05', 'Working', 'Other', 'Attended component meeting', 'Encountered issues with state management', 'Focus on testing tomorrow'),
(6, '2025-09-17', 'Working', 'Backend', 'Optimized dashboard database queries', 'Pending integration integration', 'Plan to coding'),
(3, '2025-09-09', 'Working', 'Frontend', 'Fixed login component styling', 'Debugging integration problem', 'Next, will work on review'),
(8, '2025-09-17', 'Working', 'UIUX', 'Improved model user interaction flows', 'Encountered issues with API calls', 'Focus on documentation tomorrow'),
(6, '2025-10-11', 'WFH', 'DevOps', 'Resolved login deployment issues', 'Pending UI layout integration', 'Focus on coding tomorrow'),
(9, '2025-10-06', 'Working', 'Frontend', 'Implemented service page UI', 'Facing difficulty in data processing', 'Plan to documentation'),
(2, '2025-10-02', 'Working', 'Frontend', 'Refactored model layout for responsiveness', 'Debugging data processing problem', 'Next, will work on testing'),
(9, '2025-09-02', 'Working', 'UIUX', 'Designed UI wireframes', 'Debugging UI layout problem', 'Next, will work on design'),
(2, '2025-09-20', 'Working', 'DataScience', 'Trained feature model', 'Encountered issues with state management', 'Continue testing tasks'),
(9, '2025-09-23', 'Working', 'DataScience', 'Trained model model', 'Facing difficulty in state management', 'Next, will work on coding'),
(10, '2025-09-28', 'WFH', 'Backend', 'Optimized UI database queries', 'Encountered issues with state management', 'Next, will work on coding'),
(6, '2025-09-29', 'Working', 'DataScience', 'Performed UI data cleaning', 'Debugging API calls problem', 'Continue coding tasks'),
(3, '2025-09-30', 'WFH', 'DevOps', 'Deployed component service to staging', 'Facing difficulty in data processing', 'Next, will work on integration'),
(2, '2025-08-19', 'Working', 'Frontend', 'Refactored dashboard layout for responsiveness', 'Debugging data processing problem', 'Next, will work on design'),
(6, '2025-08-20', 'Working', 'Backend', 'Created API API endpoint', 'Pending API calls integration', 'Focus on design tomorrow'),
(9, '2025-08-26', 'Working', 'Frontend', 'Fixed login component styling', 'Debugging UI layout problem', 'Next, will work on testing'),
(7, '2025-09-14', 'WFH', 'Frontend', 'Fixed service component styling', 'Encountered issues with state management', 'Plan to testing'),
(9, '2025-08-30', 'Working', 'DataScience', 'Performed service data cleaning', 'Facing difficulty in integration', 'Continue documentation tasks'),
(4, '2025-10-09', 'Working', 'DevOps', 'Set up monitoring for component service', 'Pending API calls integration', 'Next, will work on review'),
(4, '2025-09-21', 'WFH', 'Backend', 'Created model API endpoint', 'Pending API calls integration', 'Continue design tasks'),
(1, '2025-09-12', 'WFH', 'DevOps', 'Set up monitoring for service service', 'Pending API calls integration', 'Plan to testing'),
(8, '2025-08-21', 'Working', 'DevOps', 'Deployed service service to staging', 'Debugging UI layout problem', 'Continue design tasks'),
(6, '2025-09-08', 'Working', 'DataScience', 'Evaluated feature algorithm accuracy', 'Pending state management integration', 'Continue review tasks'),
(5, '2025-09-30', 'WFH', 'DataScience', 'Evaluated feature algorithm accuracy', 'Pending state management integration', 'Focus on testing tomorrow'),
(3, '2025-08-23', 'Working', 'Other', 'Documented UI process', 'Facing difficulty in state management', 'Continue documentation tasks'),
(2, '2025-10-07', 'Working', 'Backend', 'Created UI API endpoint', 'Debugging UI layout problem', 'Focus on coding tomorrow'),
(3, '2025-09-05', 'Working', 'Frontend', 'Added model button functionality', 'Encountered issues with API calls', 'Focus on documentation tomorrow'),
(2, '2025-09-22', 'Working', 'DataScience', 'Evaluated API algorithm accuracy', 'Pending data processing integration', 'Next, will work on review'),
(6, '2025-10-14', 'Working', 'DataScience', 'Performed service data cleaning', 'Encountered issues with state management', 'Plan to review'),
(4, '2025-10-12', 'Working', 'Frontend', 'Added model button functionality', 'Facing difficulty in API calls', 'Continue documentation tasks'),
(5, '2025-09-17', 'WFH', 'Frontend', 'Refactored login layout for responsiveness', 'Facing difficulty in UI layout', 'Next, will work on integration'),
(10, '2025-09-10', 'WFH', 'DataScience', 'Conducted feature engineering on model dataset', 'Facing difficulty in deployment', 'Continue testing tasks'),
(4, '2025-09-05', 'Working', 'Backend', 'Integrated component module with authentication', 'Debugging data processing problem', 'Focus on documentation tomorrow'),
(7, '2025-10-18', 'Working', 'Backend', 'Implemented feature service logic', 'Pending API calls integration', 'Next, will work on design'),
(2, '2025-08-22', 'Working', 'Backend', 'Implemented component service logic', 'Debugging API calls problem', 'Plan to review'),
(6, '2025-08-31', 'Working', 'Frontend', 'Fixed dashboard component styling', 'Debugging UI layout problem', 'Plan to documentation'),
(2, '2025-10-18', 'WFH', 'UIUX', 'Designed dashboard wireframes', 'Facing difficulty in state management', 'Continue coding tasks'),
(5, '2025-09-19', 'Leave', 'Other', 'Reviewed API pull requests', 'Encountered issues with data processing', 'Continue review tasks'),
(2, '2025-10-12', 'Working', 'DevOps', 'Configured component CI/CD pipeline', 'Facing difficulty in UI layout', 'Continue design tasks'),
(9, '2025-08-19', 'Working', 'DataScience', 'Performed login data cleaning', 'Facing difficulty in data processing', 'Focus on testing tomorrow'),
(7, '2025-10-03', 'Leave', 'DataScience', 'Trained dashboard model', 'Debugging deployment problem', 'Next, will work on design'),
(8, '2025-10-19', 'Working', 'DevOps', 'Set up monitoring for login service', 'Encountered issues with data processing', 'Continue integration tasks'),
(2, '2025-09-18', 'Working', 'DataScience', 'Trained API model', 'Facing difficulty in state management', 'Continue design tasks'),
(6, '2025-09-25', 'Working', 'DevOps', 'Resolved UI deployment issues', 'Debugging data processing problem', 'Plan to testing'),
(4, '2025-10-05', 'Working', 'DataScience', 'Conducted feature engineering on model dataset', 'Debugging data processing problem', 'Continue coding tasks'),
(2, '2025-08-30', 'Working', 'Backend', 'Optimized model database queries', 'Facing difficulty in state management', 'Next, will work on review'),
(3, '2025-09-27', 'Working', 'Other', 'Attended login meeting', 'Facing difficulty in deployment', 'Continue coding tasks'),
(9, '2025-09-03', 'Working', 'Other', 'Reviewed service pull requests', 'Debugging data processing problem', 'Next, will work on coding'),
(6, '2025-09-12', 'Working', 'DataScience', 'Evaluated UI algorithm accuracy', 'Debugging UI layout problem', 'Focus on review tomorrow'),
(1, '2025-08-31', 'Working', 'Backend', 'Integrated login module with authentication', 'Encountered issues with deployment', 'Next, will work on review'),
(7, '2025-10-03', 'Working', 'UIUX', 'Updated login mockups', 'Facing difficulty in API calls', 'Plan to integration'),
(7, '2025-10-10', 'Working', 'Frontend', 'Fixed service component styling', 'Pending state management integration', 'Plan to integration'),
(1, '2025-10-19', 'WFH', 'UIUX', 'Updated component mockups', 'Facing difficulty in state management', 'Plan to review'),
(3, '2025-09-13', 'Working', 'Other', 'Reviewed service pull requests', 'Facing difficulty in API calls', 'Next, will work on integration'),
(6, '2025-09-29', 'Working', 'Backend', 'Optimized API database queries', 'Debugging data processing problem', 'Next, will work on review'),
(2, '2025-09-24', 'Working', 'DevOps', 'Set up monitoring for model service', 'Encountered issues with API calls', 'Next, will work on design'),
(7, '2025-09-28', 'Working', 'Other', 'Reviewed component pull requests', 'Facing difficulty in integration', 'Plan to testing'),
(9, '2025-10-21', 'Working', 'DataScience', 'Trained UI model', 'Pending deployment integration', 'Continue coding tasks'),
(10, '2025-10-07', 'Working', 'Frontend', 'Fixed dashboard component styling', 'Debugging API calls problem', 'Continue coding tasks'),
(7, '2025-10-15', 'Leave', 'Other', 'Reviewed model pull requests', 'Pending integration integration', 'Plan to review'),
(8, '2025-08-21', 'Working', 'DataScience', 'Evaluated dashboard algorithm accuracy', 'Encountered issues with state management', 'Continue documentation tasks'),
(6, '2025-09-02', 'Working', 'Backend', 'Implemented feature service logic', 'Pending integration integration', 'Focus on coding tomorrow'),
(6, '2025-09-27', 'Working', 'Other', 'Attended model meeting', 'Debugging UI layout problem', 'Continue documentation tasks'),
(2, '2025-09-07', 'Working', 'DevOps', 'Configured feature CI/CD pipeline', 'Debugging data processing problem', 'Focus on testing tomorrow'),
(2, '2025-10-17', 'Working', 'Other', 'Reviewed dashboard pull requests', 'Pending integration integration', 'Focus on design tomorrow'),
(3, '2025-09-27', 'Working', 'DevOps', 'Resolved model deployment issues', 'Pending integration integration', 'Continue design tasks'),
(10, '2025-08-20', 'Working', 'UIUX', 'Improved service user interaction flows', 'Facing difficulty in UI layout', 'Continue testing tasks'),
(9, '2025-08-25', 'Working', 'UIUX', 'Designed feature wireframes', 'Facing difficulty in data processing', 'Continue documentation tasks'),
(8, '2025-08-25', 'WFH', 'Backend', 'Created service API endpoint', 'Pending integration integration', 'Plan to review'),
(6, '2025-09-11', 'Working', 'DataScience', 'Trained dashboard model', 'Pending data processing integration', 'Continue integration tasks'),
(1, '2025-10-21', 'Working', 'DevOps', 'Resolved API deployment issues', 'Encountered issues with integration', 'Plan to integration'),
(5, '2025-08-20', 'Working', 'Other', 'Worked on model task', 'Debugging integration problem', 'Plan to documentation'),
(9, '2025-09-06', 'Working', 'Backend', 'Implemented dashboard service logic', 'Pending integration integration', 'Plan to integration'),
(3, '2025-10-19', 'Working', 'UIUX', 'Designed component wireframes', 'Facing difficulty in deployment', 'Continue documentation tasks'),
(4, '2025-09-24', 'Working', 'DataScience', 'Trained feature model', 'Facing difficulty in state management', 'Focus on coding tomorrow'),
(3, '2025-08-28', 'Working', 'UIUX', 'Updated feature mockups', 'Pending integration integration', 'Continue testing tasks'),
(10, '2025-09-11', 'Working', 'UIUX', 'Designed login wireframes', 'Debugging integration problem', 'Continue coding tasks'),
(10, '2025-09-03', 'Working', 'DataScience', 'Conducted feature engineering on API dataset', 'Facing difficulty in UI layout', 'Focus on coding tomorrow'),
(7, '2025-09-22', 'WFH', 'Backend', 'Optimized model database queries', 'Facing difficulty in integration', 'Continue review tasks'),
(1, '2025-09-30', 'Working', 'UIUX', 'Tested feature prototype usability', 'Debugging state management problem', 'Next, will work on documentation'),
(4, '2025-09-12', 'WFH', 'DataScience', 'Performed model data cleaning', 'Facing difficulty in deployment', 'Next, will work on integration'),
(8, '2025-09-30', 'Working', 'Frontend', 'Fixed login component styling', 'Encountered issues with integration', 'Focus on documentation tomorrow'),
(1, '2025-10-07', 'Leave', 'DevOps', 'Configured feature CI/CD pipeline', 'Encountered issues with data processing', 'Focus on testing tomorrow'),
(9, '2025-10-21', 'Working', 'UIUX', 'Designed dashboard wireframes', 'Facing difficulty in state management', 'Plan to integration'),
(7, '2025-10-10', 'Working', 'Backend', 'Optimized login database queries', 'Facing difficulty in data processing', 'Plan to integration'),
(10, '2025-09-30', 'WFH', 'UIUX', 'Updated model mockups', 'Debugging state management problem', 'Focus on review tomorrow'),
(2, '2025-10-08', 'Working', 'Backend', 'Created component API endpoint', 'Pending integration integration', 'Continue coding tasks'),
(2, '2025-09-25', 'Working', 'DevOps', 'Resolved dashboard deployment issues', 'Pending API calls integration', 'Continue testing tasks'),
(9, '2025-08-28', 'WFH', 'Backend', 'Implemented component service logic', 'Encountered issues with deployment', 'Next, will work on documentation'),
(9, '2025-09-27', 'Leave', 'DataScience', 'Trained component model', 'Debugging API calls problem', 'Plan to documentation'),
(8, '2025-09-03', 'Working', 'Frontend', 'Fixed login component styling', 'Encountered issues with UI layout', 'Focus on coding tomorrow'),
(8, '2025-10-07', 'Working', 'Other', 'Documented feature process', 'Debugging API calls problem', 'Next, will work on coding'),
(4, '2025-08-25', 'Working', 'UIUX', 'Improved service user interaction flows', 'Encountered issues with UI layout', 'Plan to review'),
(2, '2025-08-21', 'Working', 'Other', 'Reviewed dashboard pull requests', 'Debugging data processing problem', 'Focus on review tomorrow'),
(5, '2025-09-26', 'Working', 'Frontend', 'Implemented API page UI', 'Encountered issues with state management', 'Continue testing tasks'),
(8, '2025-09-19', 'Working', 'DataScience', 'Trained model model', 'Pending data processing integration', 'Plan to review'),
(6, '2025-09-01', 'Working', 'Other', 'Reviewed service pull requests', 'Encountered issues with API calls', 'Focus on testing tomorrow'),
(8, '2025-09-30', 'WFH', 'DevOps', 'Resolved model deployment issues', 'Debugging deployment problem', 'Continue coding tasks'),
(10, '2025-10-17', 'Working', 'Backend', 'Integrated dashboard module with authentication', 'Pending state management integration', 'Plan to coding'),
(7, '2025-10-15', 'Working', 'DevOps', 'Set up monitoring for API service', 'Encountered issues with UI layout', 'Continue coding tasks'),
(4, '2025-10-02', 'WFH', 'UIUX', 'Designed UI wireframes', 'Debugging deployment problem', 'Next, will work on integration'),
(4, '2025-10-13', 'Working', 'Frontend', 'Refactored feature layout for responsiveness', 'Facing difficulty in state management', 'Continue integration tasks'),
(10, '2025-09-22', 'Working', 'UIUX', 'Designed service wireframes', 'Facing difficulty in deployment', 'Continue testing tasks'),
(9, '2025-09-12', 'Working', 'DataScience', 'Performed service data cleaning', 'Pending integration integration', 'Focus on coding tomorrow'),
(6, '2025-08-20', 'Working', 'DevOps', 'Configured feature CI/CD pipeline', 'Encountered issues with API calls', 'Continue design tasks'),
(8, '2025-08-19', 'Working', 'Frontend', 'Implemented feature page UI', 'Pending deployment integration', 'Next, will work on design'),
(5, '2025-09-13', 'Working', 'UIUX', 'Updated model mockups', 'Debugging state management problem', 'Continue coding tasks'),
(6, '2025-09-13', 'Working', 'Backend', 'Optimized API database queries', 'Pending data processing integration', 'Plan to coding'),
(2, '2025-09-10', 'Working', 'Frontend', 'Refactored component layout for responsiveness', 'Encountered issues with data processing', 'Plan to review'),
(8, '2025-10-16', 'Working', 'Backend', 'Optimized service database queries', 'Encountered issues with UI layout', 'Next, will work on design'),
(8, '2025-09-11', 'Working', 'Frontend', 'Added model button functionality', 'Facing difficulty in deployment', 'Plan to coding'),
(3, '2025-09-18', 'Working', 'DataScience', 'Performed login data cleaning', 'Pending API calls integration', 'Next, will work on integration'),
(5, '2025-09-29', 'Working', 'Backend', 'Integrated dashboard module with authentication', 'Pending API calls integration', 'Plan to integration'),
(8, '2025-09-28', 'Working', 'DevOps', 'Resolved component deployment issues', 'Encountered issues with integration', 'Next, will work on documentation'),
(3, '2025-08-24', 'Working', 'DataScience', 'Conducted feature engineering on dashboard dataset', 'Encountered issues with state management', 'Focus on documentation tomorrow'),
(5, '2025-09-12', 'Leave', 'UIUX', 'Designed UI wireframes', 'Pending API calls integration', 'Continue documentation tasks'),
(8, '2025-09-30', 'Leave', 'DevOps', 'Deployed feature service to staging', 'Facing difficulty in API calls', 'Next, will work on testing'),
(9, '2025-09-14', 'Working', 'UIUX', 'Updated component mockups', 'Encountered issues with data processing', 'Plan to testing'),
(10, '2025-09-30', 'Working', 'Backend', 'Created model API endpoint', 'Pending deployment integration', 'Next, will work on review'),
(5, '2025-10-12', 'Working', 'DataScience', 'Trained feature model', 'Pending deployment integration', 'Continue testing tasks'),
(9, '2025-08-23', 'Working', 'Other', 'Attended login meeting', 'Facing difficulty in UI layout', 'Continue coding tasks'),
(3, '2025-09-09', 'Working', 'UIUX', 'Designed login wireframes', 'Debugging integration problem', 'Focus on testing tomorrow'),
(5, '2025-09-10', 'Working', 'DevOps', 'Deployed component service to staging', 'Encountered issues with UI layout', 'Next, will work on documentation'),
(9, '2025-10-03', 'Working', 'Frontend', 'Implemented feature page UI', 'Debugging data processing problem', 'Continue testing tasks'),
(7, '2025-08-22', 'WFH', 'DataScience', 'Performed dashboard data cleaning', 'Facing difficulty in deployment', 'Next, will work on design'),
(7, '2025-08-28', 'Working', 'Frontend', 'Added UI button functionality', 'Pending API calls integration', 'Next, will work on documentation'),
(1, '2025-10-11', 'Working', 'Other', 'Reviewed dashboard pull requests', 'Debugging state management problem', 'Plan to integration'),
(6, '2025-10-21', 'Working', 'Backend', 'Created login API endpoint', 'Debugging integration problem', 'Next, will work on integration'),
(10, '2025-10-18', 'Working', 'Other', 'Reviewed UI pull requests', 'Encountered issues with integration', 'Continue integration tasks'),
(3, '2025-10-21', 'WFH', 'Backend', 'Implemented API service logic', 'Pending integration integration', 'Plan to documentation'),
(9, '2025-09-22', 'WFH', 'Other', 'Documented service process', 'Debugging data processing problem', 'Next, will work on review'),
(10, '2025-08-19', 'Working', 'UIUX', 'Tested model prototype usability', 'Facing difficulty in data processing', 'Continue design tasks'),
(1, '2025-08-24', 'WFH', 'Frontend', 'Refactored component layout for responsiveness', 'Pending integration integration', 'Continue testing tasks'),
(8, '2025-10-17', 'WFH', 'DevOps', 'Deployed component service to staging', 'Encountered issues with UI layout', 'Next, will work on documentation'),
(5, '2025-08-29', 'Working', 'UIUX', 'Updated dashboard mockups', 'Encountered issues with API calls', 'Continue design tasks'),
(10, '2025-08-23', 'WFH', 'DataScience', 'Evaluated feature algorithm accuracy', 'Facing difficulty in data processing', 'Continue testing tasks'),
(6, '2025-09-13', 'WFH', 'UIUX', 'Tested component prototype usability', 'Encountered issues with data processing', 'Focus on review tomorrow'),
(9, '2025-10-02', 'WFH', 'DataScience', 'Conducted feature engineering on dashboard dataset', 'Pending UI layout integration', 'Continue review tasks'),
(7, '2025-09-01', 'Working', 'Other', 'Documented API process', 'Pending integration integration', 'Continue integration tasks'),
(1, '2025-09-28', 'Working', 'Other', 'Reviewed dashboard pull requests', 'Debugging integration problem', 'Continue design tasks'),
(2, '2025-10-08', 'Working', 'Frontend', 'Added dashboard button functionality', 'Pending API calls integration', 'Focus on documentation tomorrow'),
(10, '2025-08-28', 'Working', 'DataScience', 'Evaluated service algorithm accuracy', 'Pending state management integration', 'Continue review tasks'),
(8, '2025-08-20', 'Working', 'UIUX', 'Tested UI prototype usability', 'Pending state management integration', 'Plan to coding'),
(2, '2025-10-08', 'Leave', 'UIUX', 'Designed UI wireframes', 'Encountered issues with UI layout', 'Continue coding tasks'),
(8, '2025-10-12', 'Working', 'Frontend', 'Refactored service layout for responsiveness', 'Debugging data processing problem', 'Focus on testing tomorrow'),
(3, '2025-09-08', 'Working', 'DevOps', 'Resolved dashboard deployment issues', 'Pending integration integration', 'Focus on testing tomorrow'),
(7, '2025-10-17', 'WFH', 'DevOps', 'Resolved API deployment issues', 'Debugging integration problem', 'Next, will work on testing'),
(6, '2025-09-07', 'Working', 'DataScience', 'Evaluated API algorithm accuracy', 'Debugging state management problem', 'Focus on testing tomorrow'),
(7, '2025-09-08', 'Working', 'UIUX', 'Tested UI prototype usability', 'Debugging deployment problem', 'Continue design tasks'),
(5, '2025-09-16', 'Working', 'Backend', 'Implemented model service logic', 'Encountered issues with deployment', 'Continue documentation tasks'),
(4, '2025-08-30', 'Working', 'DevOps', 'Resolved UI deployment issues', 'Encountered issues with UI layout', 'Plan to integration'),
(6, '2025-09-11', 'Working', 'DataScience', 'Trained API model', 'Pending state management integration', 'Continue documentation tasks'),
(3, '2025-09-21', 'Working', 'Other', 'Worked on feature task', 'Pending state management integration', 'Focus on design tomorrow'),
(7, '2025-08-20', 'Working', 'UIUX', 'Designed UI wireframes', 'Debugging state management problem', 'Plan to coding'),
(3, '2025-09-26', 'Working', 'DataScience', 'Conducted feature engineering on feature dataset', 'Debugging data processing problem', 'Focus on testing tomorrow'),
(2, '2025-09-11', 'Leave', 'UIUX', 'Designed component wireframes', 'Encountered issues with integration', 'Continue review tasks'),
(9, '2025-09-14', 'WFH', 'DataScience', 'Conducted feature engineering on API dataset', 'Pending UI layout integration', 'Focus on coding tomorrow'),
(4, '2025-08-23', 'Working', 'UIUX', 'Designed login wireframes', 'Debugging deployment problem', 'Continue design tasks'),
(7, '2025-10-13', 'Leave', 'UIUX', 'Improved model user interaction flows', 'Debugging UI layout problem', 'Continue testing tasks'),
(6, '2025-10-03', 'Working', 'Backend', 'Integrated feature module with authentication', 'Encountered issues with state management', 'Next, will work on review'),
(10, '2025-08-19', 'Leave', 'DataScience', 'Trained dashboard model', 'Facing difficulty in API calls', 'Next, will work on testing'),
(3, '2025-08-19', 'Working', 'Other', 'Worked on UI task', 'Pending API calls integration', 'Focus on design tomorrow'),
(7, '2025-08-29', 'Leave', 'DevOps', 'Deployed dashboard service to staging', 'Debugging API calls problem', 'Continue integration tasks'),
(9, '2025-08-21', 'WFH', 'Backend', 'Integrated model module with authentication', 'Encountered issues with state management', 'Focus on integration tomorrow'),
(5, '2025-09-28', 'Working', 'Other', 'Reviewed component pull requests', 'Encountered issues with data processing', 'Plan to testing'),
(4, '2025-08-28', 'Leave', 'Backend', 'Implemented service service logic', 'Debugging integration problem', 'Plan to testing'),
(5, '2025-09-08', 'Leave', 'Other', 'Reviewed service pull requests', 'Encountered issues with state management', 'Focus on integration tomorrow'),
(7, '2025-08-30', 'Working', 'Other', 'Worked on dashboard task', 'Encountered issues with deployment', 'Next, will work on integration'),
(8, '2025-08-22', 'Working', 'Backend', 'Optimized feature database queries', 'Debugging integration problem', 'Plan to integration'),
(10, '2025-09-28', 'Leave', 'Backend', 'Integrated component module with authentication', 'Debugging state management problem', 'Continue integration tasks'),
(7, '2025-10-21', 'Working', 'UIUX', 'Improved feature user interaction flows', 'Pending API calls integration', 'Plan to coding'),
(8, '2025-09-10', 'Working', 'DevOps', 'Configured model CI/CD pipeline', 'Encountered issues with UI layout', 'Next, will work on integration'),
(1, '2025-09-13', 'Leave', 'Backend', 'Created model API endpoint', 'Facing difficulty in deployment', 'Next, will work on integration'),
(5, '2025-09-10', 'WFH', 'DataScience', 'Conducted feature engineering on component dataset', 'Debugging data processing problem', 'Next, will work on documentation'),
(10, '2025-09-06', 'Working', 'DevOps', 'Resolved model deployment issues', 'Encountered issues with data processing', 'Continue integration tasks'),
(1, '2025-09-25', 'Working', 'UIUX', 'Improved login user interaction flows', 'Facing difficulty in integration', 'Continue coding tasks'),
(9, '2025-09-30', 'Working', 'DevOps', 'Resolved feature deployment issues', 'Encountered issues with state management', 'Continue documentation tasks'),
(4, '2025-10-20', 'WFH', 'Other', 'Reviewed dashboard pull requests', 'Pending API calls integration', 'Plan to testing'),
(3, '2025-09-28', 'Working', 'Backend', 'Integrated login module with authentication', 'Facing difficulty in deployment', 'Continue integration tasks'),
(2, '2025-09-11', 'Leave', 'Backend', 'Integrated UI module with authentication', 'Debugging API calls problem', 'Focus on design tomorrow'),
(4, '2025-09-03', 'Working', 'Frontend', 'Added dashboard button functionality', 'Pending data processing integration', 'Focus on testing tomorrow'),
(9, '2025-08-20', 'WFH', 'DataScience', 'Trained model model', 'Facing difficulty in state management', 'Plan to integration'),
(8, '2025-09-26', 'Working', 'UIUX', 'Updated feature mockups', 'Pending data processing integration', 'Next, will work on coding'),
(8, '2025-09-04', 'Working', 'Backend', 'Optimized login database queries', 'Debugging API calls problem', 'Next, will work on review'),
(4, '2025-09-11', 'Working', 'Frontend', 'Added feature button functionality', 'Encountered issues with state management', 'Focus on review tomorrow'),
(4, '2025-09-29', 'Working', 'DevOps', 'Resolved feature deployment issues', 'Debugging integration problem', 'Next, will work on design'),
(9, '2025-09-24', 'Working', 'Other', 'Reviewed login pull requests', 'Facing difficulty in integration', 'Continue design tasks'),
(9, '2025-09-07', 'Leave', 'DataScience', 'Performed component data cleaning', 'Debugging state management problem', 'Continue integration tasks'),
(1, '2025-08-22', 'Leave', 'DataScience', 'Performed login data cleaning', 'Pending data processing integration', 'Continue design tasks'),
(6, '2025-10-14', 'WFH', 'Other', 'Attended login meeting', 'Pending API calls integration', 'Continue testing tasks'),
(8, '2025-10-14', 'WFH', 'Backend', 'Created service API endpoint', 'Pending UI layout integration', 'Continue review tasks'),
(6, '2025-10-02', 'WFH', 'Frontend', 'Implemented API page UI', 'Debugging UI layout problem', 'Plan to integration'),
(2, '2025-09-24', 'Working', 'Frontend', 'Fixed login component styling', 'Debugging API calls problem', 'Continue coding tasks'),
(9, '2025-10-06', 'WFH', 'Backend', 'Optimized component database queries', 'Pending API calls integration', 'Plan to coding'),
(4, '2025-09-20', 'Working', 'DataScience', 'Evaluated UI algorithm accuracy', 'Facing difficulty in state management', 'Next, will work on testing'),
(1, '2025-09-25', 'WFH', 'DataScience', 'Performed dashboard data cleaning', 'Encountered issues with state management', 'Next, will work on coding'),
(9, '2025-10-08', 'Working', 'Frontend', 'Implemented login page UI', 'Facing difficulty in API calls', 'Plan to coding'),
(3, '2025-08-23', 'Working', 'UIUX', 'Designed component wireframes', 'Encountered issues with integration', 'Next, will work on testing'),
(6, '2025-09-03', 'Working', 'DataScience', 'Conducted feature engineering on API dataset', 'Facing difficulty in state management', 'Plan to documentation'),
(4, '2025-09-26', 'Leave', 'Other', 'Reviewed UI pull requests', 'Encountered issues with state management', 'Continue integration tasks'),
(6, '2025-10-12', 'Working', 'DataScience', 'Trained dashboard model', 'Debugging API calls problem', 'Focus on design tomorrow'),
(8, '2025-08-30', 'Working', 'DataScience', 'Evaluated UI algorithm accuracy', 'Pending UI layout integration', 'Next, will work on coding'),
(8, '2025-08-27', 'Working', 'Backend', 'Integrated API module with authentication', 'Facing difficulty in deployment', 'Next, will work on coding'),
(5, '2025-10-09', 'Working', 'DevOps', 'Resolved login deployment issues', 'Facing difficulty in deployment', 'Continue design tasks'),
(3, '2025-09-25', 'WFH', 'UIUX', 'Updated UI mockups', 'Encountered issues with data processing', 'Continue review tasks'),
(9, '2025-10-17', 'Working', 'Backend', 'Implemented dashboard service logic', 'Encountered issues with UI layout', 'Focus on coding tomorrow'),
(1, '2025-10-10', 'WFH', 'UIUX', 'Tested model prototype usability', 'Facing difficulty in state management', 'Focus on review tomorrow'),
(8, '2025-08-22', 'Working', 'Frontend', 'Refactored login layout for responsiveness', 'Pending integration integration', 'Plan to testing'),
(1, '2025-09-30', 'Working', 'DataScience', 'Performed dashboard data cleaning', 'Debugging data processing problem', 'Focus on review tomorrow'),
(4, '2025-09-13', 'Working', 'DevOps', 'Deployed component service to staging', 'Facing difficulty in API calls', 'Continue integration tasks'),
(3, '2025-10-15', 'Working', 'UIUX', 'Tested service prototype usability', 'Pending state management integration', 'Plan to documentation'),
(10, '2025-10-13', 'Working', 'DevOps', 'Configured service CI/CD pipeline', 'Pending data processing integration', 'Next, will work on documentation'),
(9, '2025-09-15', 'Leave', 'DevOps', 'Configured model CI/CD pipeline', 'Encountered issues with deployment', 'Plan to testing'),
(7, '2025-10-03', 'Leave', 'Backend', 'Implemented component service logic', 'Debugging UI layout problem', 'Focus on coding tomorrow'),
(2, '2025-10-02', 'Working', 'DevOps', 'Deployed login service to staging', 'Facing difficulty in integration', 'Plan to review'),
(1, '2025-09-22', 'Working', 'Other', 'Reviewed service pull requests', 'Facing difficulty in data processing', 'Continue design tasks'),
(8, '2025-10-04', 'Working', 'DataScience', 'Evaluated component algorithm accuracy', 'Pending UI layout integration', 'Next, will work on design'),
(4, '2025-08-29', 'Working', 'DevOps', 'Configured API CI/CD pipeline', 'Debugging data processing problem', 'Next, will work on integration'),
(8, '2025-08-27', 'WFH', 'Backend', 'Optimized UI database queries', 'Debugging integration problem', 'Next, will work on coding'),
(10, '2025-10-07', 'Working', 'DataScience', 'Trained service model', 'Facing difficulty in state management', 'Plan to design'),
(8, '2025-08-19', 'WFH', 'Backend', 'Optimized model database queries', 'Debugging API calls problem', 'Next, will work on review'),
(4, '2025-10-01', 'Working', 'DataScience', 'Evaluated login algorithm accuracy', 'Encountered issues with integration', 'Focus on design tomorrow'),
(7, '2025-10-01', 'Working', 'Other', 'Worked on component task', 'Pending deployment integration', 'Plan to review'),
(6, '2025-10-17', 'Working', 'Other', 'Documented feature process', 'Debugging data processing problem', 'Next, will work on review'),
(2, '2025-09-17', 'Working', 'DataScience', 'Evaluated component algorithm accuracy', 'Pending API calls integration', 'Continue integration tasks'),
(9, '2025-08-25', 'WFH', 'UIUX', 'Tested login prototype usability', 'Pending integration integration', 'Continue integration tasks'),
(9, '2025-10-07', 'Working', 'DataScience', 'Trained feature model', 'Debugging data processing problem', 'Next, will work on coding'),
(8, '2025-10-17', 'Working', 'DataScience', 'Evaluated service algorithm accuracy', 'Pending UI layout integration', 'Next, will work on documentation'),
(2, '2025-08-24', 'WFH', 'Backend', 'Implemented UI service logic', 'Debugging data processing problem', 'Next, will work on documentation'),
(8, '2025-10-19', 'Leave', 'Backend', 'Integrated model module with authentication', 'Encountered issues with data processing', 'Plan to coding'),
(7, '2025-09-22', 'Working', 'DevOps', 'Resolved API deployment issues', 'Encountered issues with integration', 'Next, will work on integration'),
(7, '2025-08-20', 'Working', 'DevOps', 'Configured service CI/CD pipeline', 'Encountered issues with UI layout', 'Plan to documentation'),
(6, '2025-09-20', 'Working', 'Frontend', 'Implemented UI page UI', 'Debugging data processing problem', 'Plan to coding'),
(2, '2025-09-07', 'Working', 'Frontend', 'Added component button functionality', 'Facing difficulty in integration', 'Plan to coding'),
(6, '2025-08-19', 'Working', 'Backend', 'Implemented component service logic', 'Pending API calls integration', 'Continue integration tasks'),
(4, '2025-08-25', 'Working', 'Backend', 'Optimized API database queries', 'Encountered issues with UI layout', 'Next, will work on review'),
(8, '2025-10-08', 'Working', 'Other', 'Documented API process', 'Facing difficulty in deployment', 'Plan to design'),
(2, '2025-10-13', 'Working', 'Backend', 'Integrated feature module with authentication', 'Pending state management integration', 'Continue design tasks'),
(6, '2025-10-20', 'Working', 'DataScience', 'Performed service data cleaning', 'Facing difficulty in integration', 'Focus on testing tomorrow'),
(9, '2025-09-29', 'Working', 'Backend', 'Optimized service database queries', 'Facing difficulty in UI layout', 'Plan to integration'),
(5, '2025-08-22', 'Working', 'Other', 'Worked on UI task', 'Facing difficulty in UI layout', 'Plan to documentation'),
(7, '2025-09-22', 'Working', 'DataScience', 'Evaluated service algorithm accuracy', 'Facing difficulty in API calls', 'Continue integration tasks'),
(3, '2025-10-13', 'Working', 'Backend', 'Optimized UI database queries', 'Pending integration integration', 'Continue coding tasks'),
(10, '2025-09-30', 'Working', 'Frontend', 'Added UI button functionality', 'Facing difficulty in deployment', 'Plan to documentation'),
(4, '2025-08-27', 'Leave', 'Frontend', 'Fixed model component styling', 'Pending integration integration', 'Plan to documentation'),
(5, '2025-09-14', 'Working', 'Backend', 'Optimized service database queries', 'Debugging deployment problem', 'Plan to design'),
(4, '2025-08-19', 'WFH', 'Backend', 'Optimized component database queries', 'Pending integration integration', 'Focus on integration tomorrow'),
(1, '2025-08-19', 'Working', 'DevOps', 'Configured API CI/CD pipeline', 'Facing difficulty in data processing', 'Next, will work on design'),
(5, '2025-09-29', 'Working', 'Other', 'Documented model process', 'Facing difficulty in state management', 'Plan to design'),
(5, '2025-08-24', 'Working', 'DataScience', 'Trained component model', 'Pending UI layout integration', 'Plan to testing'),
(9, '2025-09-16', 'Working', 'DevOps', 'Configured feature CI/CD pipeline', 'Encountered issues with data processing', 'Next, will work on coding'),
(3, '2025-09-02', 'Working', 'Other', 'Reviewed UI pull requests', 'Debugging UI layout problem', 'Focus on testing tomorrow'),
(4, '2025-10-10', 'Working', 'UIUX', 'Tested API prototype usability', 'Encountered issues with state management', 'Next, will work on design'),
(4, '2025-10-07', 'WFH', 'Other', 'Worked on model task', 'Debugging UI layout problem', 'Continue review tasks'),
(3, '2025-10-07', 'Working', 'Frontend', 'Added login button functionality', 'Pending UI layout integration', 'Continue design tasks'),
(9, '2025-09-11', 'Working', 'DataScience', 'Conducted feature engineering on service dataset', 'Debugging API calls problem', 'Next, will work on design'),
(5, '2025-10-05', 'Working', 'DataScience', 'Conducted feature engineering on dashboard dataset', 'Debugging deployment problem', 'Continue review tasks'),
(6, '2025-10-03', 'Working', 'Other', 'Worked on component task', 'Encountered issues with integration', 'Plan to testing'),
(2, '2025-10-08', 'Working', 'Frontend', 'Fixed API component styling', 'Encountered issues with data processing', 'Plan to review'),
(8, '2025-09-14', 'Working', 'Frontend', 'Implemented UI page UI', 'Pending state management integration', 'Continue documentation tasks'),
(5, '2025-09-12', 'WFH', 'Other', 'Reviewed feature pull requests', 'Facing difficulty in state management', 'Plan to coding'),
(6, '2025-08-19', 'Working', 'DevOps', 'Configured feature CI/CD pipeline', 'Debugging deployment problem', 'Plan to review'),
(5, '2025-10-03', 'Working', 'Frontend', 'Added feature button functionality', 'Pending data processing integration', 'Plan to coding'),
(7, '2025-09-26', 'Working', 'Backend', 'Implemented UI service logic', 'Pending data processing integration', 'Plan to review'),
(8, '2025-09-02', 'Working', 'DataScience', 'Conducted feature engineering on service dataset', 'Pending UI layout integration', 'Next, will work on integration'),
(3, '2025-09-13', 'Working', 'DataScience', 'Evaluated model algorithm accuracy', 'Pending integration integration', 'Plan to coding'),
(2, '2025-09-10', 'Leave', 'DevOps', 'Deployed API service to staging', 'Debugging state management problem', 'Next, will work on coding'),
(5, '2025-09-18', 'Working', 'Frontend', 'Added component button functionality', 'Facing difficulty in integration', 'Continue design tasks'),
(8, '2025-10-13', 'Working', 'Backend', 'Created dashboard API endpoint', 'Encountered issues with API calls', 'Continue coding tasks'),
(7, '2025-10-03', 'Working', 'Backend', 'Created model API endpoint', 'Pending data processing integration', 'Plan to integration'),
(6, '2025-10-02', 'Working', 'DataScience', 'Trained feature model', 'Facing difficulty in integration', 'Continue design tasks'),
(1, '2025-09-19', 'Leave', 'DevOps', 'Configured feature CI/CD pipeline', 'Pending UI layout integration', 'Continue documentation tasks'),
(8, '2025-09-07', 'Working', 'Backend', 'Implemented model service logic', 'Debugging API calls problem', 'Focus on review tomorrow'),
(1, '2025-09-06', 'Working', 'DevOps', 'Configured UI CI/CD pipeline', 'Encountered issues with integration', 'Plan to integration'),
(6, '2025-09-25', 'Working', 'Backend', 'Optimized login database queries', 'Facing difficulty in deployment', 'Continue review tasks'),
(3, '2025-10-11', 'Working', 'DevOps', 'Set up monitoring for login service', 'Facing difficulty in UI layout', 'Focus on testing tomorrow'),
(3, '2025-10-05', 'Working', 'UIUX', 'Updated API mockups', 'Facing difficulty in UI layout', 'Focus on review tomorrow'),
(8, '2025-08-23', 'Working', 'Other', 'Documented service process', 'Debugging data processing problem', 'Next, will work on documentation'),
(6, '2025-09-05', 'Working', 'DataScience', 'Evaluated UI algorithm accuracy', 'Pending data processing integration', 'Continue coding tasks'),
(2, '2025-08-31', 'Working', 'UIUX', 'Improved feature user interaction flows', 'Pending state management integration', 'Focus on integration tomorrow'),
(7, '2025-09-30', 'Working', 'Other', 'Attended component meeting', 'Encountered issues with deployment', 'Next, will work on integration'),
(5, '2025-09-12', 'WFH', 'UIUX', 'Tested API prototype usability', 'Debugging UI layout problem', 'Focus on coding tomorrow'),
(6, '2025-10-11', 'Working', 'Frontend', 'Implemented dashboard page UI', 'Facing difficulty in deployment', 'Plan to review'),
(7, '2025-09-06', 'Working', 'Other', 'Attended component meeting', 'Facing difficulty in API calls', 'Next, will work on review'),
(10, '2025-10-11', 'Leave', 'DevOps', 'Set up monitoring for component service', 'Facing difficulty in integration', 'Focus on coding tomorrow'),
(10, '2025-09-21', 'Leave', 'DataScience', 'Evaluated model algorithm accuracy', 'Facing difficulty in UI layout', 'Next, will work on design'),
(4, '2025-10-03', 'Working', 'DevOps', 'Deployed API service to staging', 'Debugging deployment problem', 'Plan to review'),
(3, '2025-10-08', 'Working', 'DevOps', 'Deployed component service to staging', 'Facing difficulty in UI layout', 'Continue integration tasks');
